[package]
name = "lightweight_web"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "main"
path = "src/entry/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cali_derive = { version = "*", path = "../../cali/derive" }
cali_core = { version = "*", path = "../../cali/core" }
lightweight_store = { version = "*", path = "../store" }
lightweight_core = { version = "*", path = "../core" }

rust-argon2 = "1.0"
thiserror = "1.0"
tokio = { version = "1.32", features = ["rt-multi-thread", "time", "macros", "signal", "process"] }
tonic = { version = "0.9.2", features = ["tls", "codegen"] }
jwt = "0.16.0"
hmac = "0.12.1"
sha2 = "0.10.7"
rand = "0.8.5"
prost = "0.11.9"
prost-types = "0.11.9"
sqlx = { version = "0.7.1", default-features = false, features = ["runtime-tokio-native-tls", "mysql", "chrono", "bigdecimal", "macros", "migrate"] }
chrono = "0.4.26"
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
serde_derive = "1"
serde_ignored = "0.1"
clap = "3.2.17"
log = "0.4.17"

[dev-dependencies]
url = "2.4.0"

[build-dependencies]
cali_derive = { version = "*", path = "../../cali/derive" }
cali_core = { version = "*", path = "../../cali/core" }
tonic-build = "0.9.2"
convert_case = "0.5.0"
